<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>API</AssemblyName>
        <RootNamespace>API</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Base\Base.csproj" />
    </ItemGroup>

</Project>
